### ISSUE TITLE
Options window

### ISSUE THREAD

**Issue by Hughmon** [MoneroOcean/nodejs-pool#23]
Options window automatically minimises after entering password. Make it stay open as this causes some confusion, as seen in discord chat ;)

**Comment by bobbieltd** [comment]
Ouff, here is not poolui GUI github. However, can you describe more about confusion ? What should website do after password entered ?

**Comment by bobbieltd** [comment]
Confusion will make miners reclick the icon. What a surprise ! Successful 😂

**Comment by Hughmon** [comment]
My suggestion would be not to minimise the window after entering the password. I would think that the most common reason for click the options button is to change the payment threshold, so why not bring you straight there. It's not like you're unlocking superuser mode or something. My apologies for posting in the wrong section, where is pool gui hub?

**Comment by Hughmon** [comment]
Confusion wise i'm just observing technical_support chat on discord. Being one, here is some end user POV. The options button has a lock icon, so when click it and enter your password it feels like you've unlocked some advanced options, and having to click the same button again is slightly counterintuitive.

**Comment by MoneroOcean** [comment]
It OK place to put GUI based suggestion as well since I do not have separate GUI repo (I'm shy to show my rather messy changes on GUI side). I've just implemented your suggestion (may work only under incognito for a while): after you enter correct password "Miner Options" window opens automatically so you do not have to click it separately each time. Will close this issue if I will get confirmation that all is fine.

**Comment by Hughmon** [comment]
It works perfectly :)

**Comment by MoneroOcean** [comment]
Great!
