### ISSUE TITLE
don't add incorrect user in table

### ISSUE THREAD

**Issue by 1rV1N-git** [MoneroOcean/nodejs-pool#9]
May it can be better don't add with incorrect email 
			let filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if (!filter.test(pass_split[1])) {
				return;
			} 

https://github.com/MoneroOcean/nodejs-pool/blob/9e8188398d36232adcdd1fe8a442fb65148f7686/lib/pool.js#L339

**Comment by MoneroOcean** [comment]
I think we should still add whatever user decided to put after : character because it can be his password, not email (or fake email). This string after : character is placed to email field by design. And I have enough problems with miners not able to set their Dashboard password to avoid adding some additional barriers on their way.

However I think it make sense to add this check at the moment we try to send email to user (and just do not try to send it in case email address is invalid for sure). What do you think?

**Comment by 1rV1N-git** [comment]
@MoneroOcean I agree with you.

**Comment by MoneroOcean** [comment]
Done: https://github.com/MoneroOcean/nodejs-pool/commit/ec9aee3c364e0f37a2016ebe11615fa6ae62ecec

**Comment by 1rV1N-git** [comment]
Thank you. 

P.S. Add me in telegram if you want. I joined to your channel.

**Comment by 1rV1N-git** [comment]
I cannot write to the channel ))

**Comment by MoneroOcean** [comment]
I'm noob at Telegram and I do not want to advertise it, so let's use Discord)
